version: "3"

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /Users/chrishardcastle/sites/freshjam/
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - ./public:/var/www
            - logs:/var/www/logs
